### ISSUE TITLE
Can't get your package

### ISSUE THREAD

**Issue by edwvee** [Macilias/go-images-orientation#1]
$ go get "github.com/macilias/go-images-orientation"
# github.com/macilias/go-images-orientation
runtime.main_main·f: relocation target main.main not defined
runtime.main_main·f: undefined: "main.main"

Looks like there is no main function, though the package's name is main. Please, fix that. Don't know how to name this package properly.

**Comment by Macilias** [comment]
provided a dummy main method to avoid the problem. 
closes #1

**Comment by edwvee** [comment]
Ok. Read your code through: looks more like an app, than a library. Can I publish a package on github based on your code with reminding this repo? Package that is a library.

**Comment by Macilias** [comment]
Its basically a lightweight util class with one important but missing method.
Of course you can use it.
Have fun

Maciek
-- 
Maciej Niemczyk 
Software Entwickler  




E-Mail: maciek.niemczyk@vitraum.de 
Internet: www.vitraum.de 

Vitraum GmbH 
Am Sandtorkai 71  
D-20457 Hamburg

Vertretungsberechtigte Geschäftsführer: Alexander Schwaab, David Ranft, Martin Treusch von Buttlar 
Amtsgericht Hamburg, Registernummer: HRB 137090

**Comment by edwvee** [comment]
https://github.com/edwvee/exiffix - so I meant this. Is it OK?
